### ISSUE TITLE
Refactor goat-data import workflow

### ISSUE THREAD

**Issue by rjchallis** [genomehubs/goat-data#98]
The goat-data import workflow could be improved by splitting file processing into file-/folder-specific pipelines to generate validated and name-checked files ready for import. This will take validation and name checking steps out of the main pipeline and allow them to be run only when the data change or when enough new taxa have been added to make a new name lookup worthwhile.

Refactoring will also make it easier to incorporate updated file processing scripts and test new data/configuration files ahead of attempting a full import.

Key steps:

- [ ] Fetch NCBI taxonomy plus extra taxa from ENA taxonomy API. Run `genomehubs init` to fill a taxonomy index. Snapshot the taxonomy index for reuse in develop, testing and production pipelines
- [ ] Test validation via `blobtk import` on all existing files
- [ ] Set up dev server from taxonomy index to run name lookup. (Long term aim is to write more efficient standalone name matching service)
- [ ] Migrate assembly parsing scripts to new pipeline. Stop adding organelle assemblies to the main index.
- [ ] Document/automate curation of taxid, synonym and spellcheck files to ensure name matching is correct. Encourage contributing sources to use taxon ID where possible.
- [ ] Set up test import pipeline using taxonomy snapshot to be run on a per file/per folder basis. Include specs for `genomehubs test` to ensure attribute values are set and can be accessed as expected.
